Importa numpy

In [1]:
import numpy as np

crea un numpy array que tenga la siguente estructura

```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```

llamalo `array`

In [2]:
array = np.array([
    [1, 6, 11],
    [2, 7, 12],
    [3, 8, 13],
    [4, 9, 14],
    [5, 10, 15]
])
array

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

averigua la forma del array

In [76]:
array.shape

(5, 3)

Selecciona la segunda columna del array

In [77]:
array[:,1]

array([ 6,  7,  8,  9, 10])

 Crea un vector con los valores del 15 al 55, llamalo array2
    
*pista: usa np.arange*

In [78]:
array2 = np.arange(15,56)
array2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

asigna el valor 23 a la quinta posicion del array2

In [80]:
array2[4] = 23
array2

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

convierte array2 del revés (es decir `[55,54,....,15]`

In [23]:
array2[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

Crea una matriz diagonal donde los elementos de la diagonal sean los 5 primeros valores pares de array2, llamala `matriz_diag`

*pista: usa np.diag*

In [41]:
np.diag?
indice_filtrado = array2 % 2 == 0
indice_filtrado

matriz_diag =np.diag(array2[indice_filtrado][:5])
matriz_diag

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

Imprime el numero de dimensiones de `matriz_diag`

In [42]:
matriz_diag.ndim

2

Crea una matriz con números aleatorios de tamaño 5x3 (4 filas por 3 columnas), llamala `matriz`

In [83]:
matriz = np.random.random_integers(10, size = (5,5))
matriz

C:\Users\jefer\AppData\Local\Temp\ipykernel_5188\1255605431.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  matriz = np.random.random_integers(10, size = (5,5))


array([[10,  4,  7,  3, 10],
       [ 2,  4,  7,  7, 10],
       [ 9, 10,  5,  4,  2],
       [ 6,  2,  9,  5,  6],
       [ 6,  7,  8,  2,  9]])

multiplica `matriz` por `matriz_diag`

In [84]:
matriz * matriz_diag

array([[160,   0,   0,   0,   0],
       [  0,  72,   0,   0,   0],
       [  0,   0, 100,   0,   0],
       [  0,   0,   0, 110,   0],
       [  0,   0,   0,   0, 216]])