In [1]:
print("hola!")

hola!


In [2]:
lista = ['ho','la']
for palabra in lista:
    print(palabra)

print(type(lista))

ho
la
<class 'list'>


In [3]:
#**Esto va en negrita**
#*Esto va en cursiva*

### Introducción a Jupyther

#- Elemento 1
#  - Elemento 1.1
    

In [4]:
import matplotlib.pyplot as plt

In [5]:
#el ? al final es para conocer la ayuda de la libreria
#plt? 

In [6]:
#%load_ext watermark
#%watermark

In [7]:
import sys
!conda install --yes --prefix {sys.prefix} numpy

Solving environment: ...working... done

# All requested packages already installed.





==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.5.0




In [8]:
import requests

In [9]:
import sys

In [10]:
import sys
!{sys.executable} -m pip install requests

In [11]:
import sys
import numpy as np

In [12]:
array_id = np.array([4.5, 3])
type(array_id)

numpy.ndarray

In [13]:
array_id.shape

(2,)

In [14]:
matriz = np.array([
    [1,2,3],
    [4,5,6]
])

In [15]:
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
matriz.ndim

2

In [17]:
matriz.shape

(2, 3)

In [18]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.ones((2))

array([1., 1.])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.random((2,3))

array([[0.54705971, 0.12022903, 0.70946045],
       [0.97917652, 0.06848578, 0.33516476]])

In [22]:
!type np_text.txt

1,2,3
43, 2,3
34,1,1
0,1,1


In [24]:
np_text = np.genfromtxt("np_text.txt", delimiter=",")
np_text

array([[ 1.,  2.,  3.],
       [43.,  2.,  3.],
       [34.,  1.,  1.],
       [ 0.,  1.,  1.]])

In [26]:
lista_2d = [[1,2,3], [4,5,6]]
array_2d = np.array ([[1,2,3], [4,5,6]])

In [27]:
sys.getsizeof(lista_2d)

72

In [28]:
sys.getsizeof(array_2d)

152

In [29]:
big_lista = list(range(1000000))
big_array = np.array(range(1000000))

In [30]:
sys.getsizeof(big_lista)

8000056

In [31]:
sys.getsizeof(big_array)

4000112

In [34]:
%%timeit

sum(range(1000000))

40.9 ms ± 3.85 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [36]:
%%timeit
np.sum(np.arange(1000000))

1.38 ms ± 32.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [38]:
np.array([1.0, 5.4], dtype=int).dtype

dtype('int32')

In [39]:
#array de strings
np.array([1.0, 2.0, "patata"])

array(['1.0', '2.0', 'patata'], dtype='<U32')

In [40]:
%%timeit
["{}".format(i) for i in range(100000)]

29.2 ms ± 342 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [41]:
f = np.vectorize(lambda x: "{}".format(x))

In [42]:
#array de strings, en este caso numpy no es tan eficiente como un array de python
%%timeit
f(np.arange(100000))

56.8 ms ± 302 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [48]:
matriz_3X4 = np.array([
    [1,2,3,4], [5,6,7,8], [9,10,11,12]
])
matriz_3X4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
#trae el primer elemento
matriz_3X4[0]

array([1, 2, 3, 4])

In [46]:
matriz_3X4[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
#de cada elemento en la lista o fila traer el segundo valor de cada una de ellas (posicion en la lista) 
matriz_3X4[:,1]

array([ 2,  6, 10])

In [49]:
#Segundo elemento de la segunda fila
matriz_3X4[1,1]

6

In [55]:
#en este caso, no se modifica el valor de la fila seleccionado en la matriz
seleccion = matriz_3X4[1,3]
print(seleccion)
seleccion=100
matriz_3X4

8


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
#sin embargo, al utilizar : (dos puntos) en vez de , (coma) y accedemos a un valor en una fila con el fin de reasignar dicho valor
#este va a cambiar tambien en la matriz por lo que no estamos haciendo una copia como en el ejemplo anterior
#tener mucho cuidado
seleccion = matriz_3X4[:2]
seleccion
seleccion[0,0] = 100
matriz_3X4

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [57]:
#proceso de filtrado
matriz_3X2 = np.array([
    [1, 4], [2, 4], [5, 0]
])
matriz_3X2

array([[1, 4],
       [2, 4],
       [5, 0]])

In [58]:
#filtro elementos mayor a 2
indice_filtrado = matriz_3X2 > 2
indice_filtrado

array([[False,  True],
       [False,  True],
       [ True, False]])

In [59]:
#se puede utilizar la variable como condicion para obtener solo los valores que los cumplan
matriz_3X2[indice_filtrado]

array([4, 4, 5])

In [66]:
#operaciones entre arrays de numpy
array1 = np.array([[1,2], [3,4]])
array2 = np.array([[23, 5], [3, 0]])

In [67]:
array1 + array2

array([[24,  7],
       [ 6,  4]])

In [68]:
array1 * array2

array([[23, 10],
       [ 9,  0]])

In [69]:
#multiplicación matricial
array1 @ array2

array([[29,  5],
       [81, 15]])

In [70]:
array1.dot(array2)

array([[29,  5],
       [81, 15]])